[profile.default]
src = 'src'
test = 'test'
libs = ['lib']
solc = "0.8.25"
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/=lib/@openzeppelin/",
    "forge-std/=lib/forge-std/"
]
